version: '3'

volumes:
  minio-data:
    driver: local

services:
  app:
    build:
      context: .
    container_name: mediabox
    depends_on:
      - minio
    ports:
      - '8080:8080'

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command:
      server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio
